GEt http://localhost:8080/users 

####
GET http://localhost:8080/users/5fe869b12538ec25e1c84fe2

###

POST  http://localhost:8080/post     
Content-Type: application/json

{
    "firstName": "louis22",
    "lastName": "nwosu22",
    "password": "12366321",
    "email": "dummy222@gmail.com"
}

###

POST  http://localhost:8080/login     
Content-Type: application/json

{
    "email": "dummy222@gmail.com",
    "password": "12366321"
}

# ###
# DELETE  http://localhost:8080/5fe8fa5d00f793176e8ceae9
