POST  http://localhost:8080/signup     
Content-Type: application/json

{
    "userName": "louis_the_writer",
    "password": "12366321",
    "email": "dummy332@gmail.com"
}

###

POST  http://localhost:8080/signin     
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "mint4coding.com"
}


####
GET http://localhost:8080/notes/getNotes/606800351b2e7118925bcfc3

###

POST  http://localhost:8080/notes/new-note/607b8b021ad06e1bf0293269  
Content-Type: application/json

{
    "title": "two more",
    "description": "lets see!"
}