POST  http://localhost:8080/signup     
Content-Type: application/json

{
    "userName": "louis_the_writer",
    "password": "12366321",
    "email": "dummy332@gmail.com"
}

###
 
POST  http://localhost:8080/signin    
Content-Type: application/json

{
    "email": "dummy332@gmail.com",
    "password": "12366321"  
}


####
GET http://localhost:8080/notes/get-notes/607b915e620b0a22805e2d4b

###

POST  http://localhost:8080/notes/new-note/607b8b021ad06e1bf0293269  
Content-Type: application/json

{
    "title": "two more",
    "description": "lets see!"
}