### request to create a new user
POST http://localhost:8080/noted/sign-up
Content-Type: application/json

{
    "email": "ronaldthedaddy@gmail.com",
    "password": "mint4coding.com",
    "username": "ghost_righter" 
}

### request to get all docs of a user
Get http://localhost:8080/noted/60e0b3c5309e501ce03fa2dc

### request to post docs of a user
Post http://localhost:8080/noted/postdoc/60def28682a97631887946c8
Content-Type: application/json

{
    "doc_type": "collection",
    "date": "13 oct 2021"
}

### get documents from a single day
GET  http://localhost:8080/noted/get-doc/60de0e2e61710a0be8778280
Content-Type: application/json

{
    "date": "5 oct 2021"
}

### get single doc @param-.. :id=docCol id, ID=doc id, date=date of doc col
GET  http://localhost:8080/noted/get-single-doc/60e0b3c5309e501ce03fa2de
Content-Type: application/json

{
    "ID": "60e0bf1d309e501ce03fa2e7",
    "date": "03-07-2021"
}
